# Specify information needed for setting up the default build environment
# At the time of this commit, the Xenial Ubuntu build environment is the 
# default environment and has gfortran 6.
dist: xenial
language: C++

# Specify four different platform/compiler combinations for
# building/testing the binary
matrix:
  include:
    - os: linux 
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-6
      env:
        - COMPILER_ENV="CC=gcc-6 && CXX=g++-6"
    - os: linux 
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - COMPILER_ENV="CC=clang-3.9 && CXX=clang++-3.9"
    - os: osx
      osx_image: xcode10
      env:
        # Update homebrew upfront so that we have a modern version
        # of ruby installed first.
        - COMPILER_ENV="brew update && brew install gcc@8 && CC=gcc-8 && CXX=g++-8"
    - os: osx
      osx_image: xcode8
      env:
        # Use the version of clang already in OS X image
        - COMPILER_ENV="CC=clang && CXX=clang++"

before_install:
- eval "${COMPILER_ENV}"
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update                   ; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y liblapack-dev ; fi
# lapack is already installed in the OS X build environment
#    => no need to use Travis CI homebrew addon to install it
#- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install lapack                   ; fi
- echo $TRAVIS_OS_NAME
- echo $CC
- echo $CXX
- $CC --version
- $CXX --version

install:
- $CC -o solve_problem.x solve_problem.c -llapack
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then otool -L $TRAVIS_BUILD_DIR/solve_problem.x ; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then ldd      $TRAVIS_BUILD_DIR/solve_problem.x ; fi

script:
- $TRAVIS_BUILD_DIR/solve_problem.x

after_success:
- echo "Success!"

after_failure:
- echo "Arrrrgggggghhhhhhh! Why?!"

after_script:
- echo "This Travis CI tutorial has come to an end..."

